### ISSUE TITLE
Hash lock secret being emitted

### ISSUE THREAD

**Issue by addywaddy** [OpenSTFoundation/openst-protocol#111]
https://github.com/OpenSTFoundation/openst-protocol/blob/334b3edffb8e43004935640661c2954ca20fe3fa/contracts/OpenSTValue.sol#L49:50

Please excuse me if I'm being a bit naive here :) The hashlocking used in Simple Token seems to share some principles outlined here for atomic cross-chain trading:

https://en.bitcoin.it/wiki/Atomic_cross-chain_trading

In this case, revealing the hashlock too soon would mean that the second party could run off with the money. Is there a similar attack vector here, as `_unlockSecret` is emitted by the `ProcessedStake` event?

**Comment by benjaminbollen** [comment]
Hi @addywaddy 

The similarities are indeed there, in the sense that the protocol creates an atomic action on two independent systems; contrary though to the referred algorithm, there is only one party involved here:  a user wants to stake $OST on Ethereum mainnet in order to obtain the equivalent value in utility tokens on the auxiliary utility chain.  When calling `ProcessStaking` or `ProcessMinting` on either side (Ethereum mainnet or the utility chain) indeed the secret is revealed for all to know - but this is the intention to have the atomic action: confirming on one side equals confirming on the other side.

So as a user, until you call any `Process_` function you want to protect your secret; revealing it once, it should be known to all, so we decided to put it in the event explicitly.  The platform APIs are built to abstract these actions for an (honest) actor
